/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.fronend.menus;

import proyectofinal.backend.Escenario.Jugador;

/**
 *
 * @author astridmc
 */
public class CompraKIt extends javax.swing.JPanel {

        private static final int PRECIO_KMENOR = 40;
    private static final int PRECIO_KMAYOR=60;
    
    
    public CompraKIt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kits = new javax.swing.ButtonGroup();
        lblTIpo = new javax.swing.JLabel();
        kitMayor = new javax.swing.JRadioButton();
        kitMenor = new javax.swing.JRadioButton();
        comprar = new javax.swing.JButton();

        setBackground(new java.awt.Color(198, 253, 220));

        lblTIpo.setFont(new java.awt.Font("Dyuthi", 0, 36)); // NOI18N
        lblTIpo.setText("QUE TIPO DE KIT DESEAS COMPRAR?");

        kitMayor.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        kitMayor.setText("KIT MAYOR (este kit repara tu vehiculo 50 puntos de vida)");

        kitMenor.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        kitMenor.setText("KIT MENOR (este kit repara tu vehiculo 25 puntos de vida)");
        kitMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitMenorActionPerformed(evt);
            }
        });

        comprar.setText("COMPRAR");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTIpo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitMayor)
                            .addComponent(kitMenor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTIpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kitMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kitMenor)
                .addGap(18, 18, 18)
                .addComponent(comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kitMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitMenorActionPerformed

    }//GEN-LAST:event_kitMenorActionPerformed

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        if(kitMayor.isSelected()){
            Jugador.jugadores.get(0).setMyOro(Jugador.jugadores.get(0).getMyOro()-PRECIO_KMAYOR);
        }else if (kitMenor.isSelected()){
            Jugador.jugadores.get(0).setMyOro(Jugador.jugadores.get(0).getMyOro()-PRECIO_KMENOR);
        }
    }//GEN-LAST:event_comprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprar;
    private javax.swing.JRadioButton kitMayor;
    private javax.swing.JRadioButton kitMenor;
    private javax.swing.ButtonGroup kits;
    private javax.swing.JLabel lblTIpo;
    // End of variables declaration//GEN-END:variables
}
