/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.fronend.menus;

import javax.swing.JOptionPane;
import proyectofinal.backend.Escenario.AlmacenArma;
import proyectofinal.backend.Escenario.Arma;
import proyectofinal.backend.Escenario.Jugador;

/**
 *
 * @author astridmc
 */
public class CreaArmas extends javax.swing.JDialog {
    
    String nombreArma ;

    /**
     * Creates new form CreaArmas
     * @param parent
     */
    public CreaArmas(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        lblGuardado.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        lblEscribe = new javax.swing.JLabel();
        txtNombreArma = new javax.swing.JTextField();
        lblGuardado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(139, 235, 206));

        jPanel1.setBackground(new java.awt.Color(129, 239, 237));

        lblTexto.setFont(new java.awt.Font("Dyuthi", 1, 48)); // NOI18N
        lblTexto.setText("CREA TUS PROPIAS ARMAS");

        lblEscribe.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        lblEscribe.setText("ESCRIBE EL NOMBRE DE TU NUEVA ARMA:");

        txtNombreArma.setFont(new java.awt.Font("Dyuthi", 0, 24)); // NOI18N
        txtNombreArma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreArmaMouseClicked(evt);
            }
        });
        txtNombreArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArmaActionPerformed(evt);
            }
        });

        lblGuardado.setText("tu arma de ha inicializado exitosamente y se le han asignado sus valores!! ");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEscribe)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreArma, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblTexto)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(223, 223, 223)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblGuardado)
                        .addGap(86, 86, 86)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTexto)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscribe)
                    .addComponent(txtNombreArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGuardado)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
         if(txtNombreArma.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nombre Requerido");
        }else{
            
            nombreArma = txtNombreArma.getText();
            Arma nuevaArma = new Arma(nombreArma);
            nuevaArma.setNombreArma(nombreArma);
            nuevaArma.agregarArmas(nuevaArma);
            lblGuardado.setVisible(true);
            txtNombreArma.setText("");
            AlmacenArma.alamacenarArmas(nuevaArma, Arma.armas);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArmaActionPerformed
       
    }//GEN-LAST:event_txtNombreArmaActionPerformed

    private void txtNombreArmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreArmaMouseClicked
        lblGuardado.setVisible(false);
    }//GEN-LAST:event_txtNombreArmaMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEscribe;
    private javax.swing.JLabel lblGuardado;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtNombreArma;
    // End of variables declaration//GEN-END:variables
}
