/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.fronend.menus;
/**
 *
 * @author astridmc
 */
public class TipoTablero extends javax.swing.JDialog {
    
    public int numeroTablero=0;
    public int elegido =0;

    public TipoTablero(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaTIpoTablero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnJungla = new javax.swing.JButton();
        btnPLaya = new javax.swing.JButton();
        btnMontañoso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(139, 235, 206));

        etiquetaTIpoTablero.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        etiquetaTIpoTablero.setText("ESCOJA EL TIPO DE TERRENO ");

        jLabel1.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        jLabel1.setText("EN EL QUE DESEA JUGAR :");

        btnJungla.setFont(new java.awt.Font("Dyuthi", 1, 24)); // NOI18N
        btnJungla.setText("JUNGLA");
        btnJungla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJunglaActionPerformed(evt);
            }
        });

        btnPLaya.setFont(new java.awt.Font("Dyuthi", 1, 24)); // NOI18N
        btnPLaya.setText("PLAYA");
        btnPLaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPLayaActionPerformed(evt);
            }
        });

        btnMontañoso.setFont(new java.awt.Font("Dyuthi", 1, 18)); // NOI18N
        btnMontañoso.setText("MONTAÑOSO");
        btnMontañoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontañosoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(etiquetaTIpoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJungla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPLaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMontañoso, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTIpoTablero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJungla, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPLaya, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMontañoso, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJunglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJunglaActionPerformed
        elegido =1;
        numeroTablero =1;
        this.setVisible(false);
    }//GEN-LAST:event_btnJunglaActionPerformed

    private void btnPLayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPLayaActionPerformed
        elegido =1;
        numeroTablero = 2;
        this.setVisible(false);
    }//GEN-LAST:event_btnPLayaActionPerformed

    private void btnMontañosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontañosoActionPerformed
        elegido =1;
        numeroTablero=3;
        this.setVisible(false);
    }//GEN-LAST:event_btnMontañosoActionPerformed

    public int getElegido() {
        return elegido;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJungla;
    private javax.swing.JButton btnMontañoso;
    private javax.swing.JButton btnPLaya;
    private javax.swing.JLabel etiquetaTIpoTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
