/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.fronend.tableros;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import proyectofinal.backend.Escenario.Vehiculo;

/**
 *
 * @author astridmc
 */
public class Dado extends javax.swing.JPanel {
int numeroSorteado = (int) (Math.random() * 5 + 1);
    /**
     * Creates new form Dado
     */
    public Dado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 42, 42));

        lblNumero.setFont(new java.awt.Font("Dyuthi", 0, 60)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void seisCaras(){
        Movimiento dado3 = new Movimiento();
        for(int i =0 ; i<numeroSorteado;i++){
            int numeroRandom = (int) (Math.random() * 5 + 1);
            lblNumero.setText(Integer.toString(numeroRandom));
            dado3.start();
        }
    }
    
    public void cienCaras(){
        Movimiento dado2 = new Movimiento();
        for(int i =0 ; i<numeroSorteado;i++){
            int numeroRandom = (int) (Math.random() * 99 + 1);
            
            lblNumero.setText(Integer.toString(numeroRandom));
            dado2.start();
            
        }
    }
    
    public void tresCaras(){
        //Movimiento dado = new Movimiento();
        for(int i =0 ; i<numeroSorteado;i++){
            int numeroRandom = (int) (Math.random() * 3 + 1);
            
            lblNumero.setText(Integer.toString(numeroRandom));
           // dado.start();
            
        }
       
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNumero;
    // End of variables declaration//GEN-END:variables
}
   class Movimiento extends Thread{

    
    @Override
    public void run(){   
            try {
                System.out.println("oooooo");
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Movimiento.class.getName()).log(Level.SEVERE, null, ex);
            }  
    
   }
}