
package proyectofinal.fronend;

import java.awt.Dimension;
import javax.swing.JPanel;
import proyectofinal.fronend.menus.CompraArmas;
import proyectofinal.fronend.menus.CompraMuniciones;


public class Tienda extends javax.swing.JDialog {
    
    CompraMuniciones municiones = new CompraMuniciones();
    CompraArmas armas = new CompraArmas();

    public JPanel getPanelOpcion() {
        return panelOpcion;
    }

    public void setPanelOpcion(JPanel panelOpcion) {
        this.panelOpcion = panelOpcion;
    }
    
    /**
     * Creates new form Tienda
     * @param parent
     */
    public Tienda(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        
        //diseño();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelInformacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listaJugador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        producto = new javax.swing.JComboBox<>();
        panelOpcion = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelInformacion.setBackground(new java.awt.Color(129, 239, 237));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("TIENDA");

        listaJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaJugadorActionPerformed(evt);
            }
        });

        jLabel2.setText("escoja su nombre Jugador");

        jLabel3.setFont(new java.awt.Font("Dyuthi", 2, 24)); // NOI18N
        jLabel3.setText("Su Oro disponible es:");

        jLabel4.setFont(new java.awt.Font("Dyuthi", 2, 24)); // NOI18N
        jLabel4.setText("Que producto deseas adquirir?");

        producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "municiones", "kits", "Arcenal", "boots" }));
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });

        panelOpcion.setBackground(new java.awt.Color(129, 239, 237));

        javax.swing.GroupLayout panelOpcionLayout = new javax.swing.GroupLayout(panelOpcion);
        panelOpcion.setLayout(panelOpcionLayout);
        panelOpcionLayout.setHorizontalGroup(
            panelOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelOpcionLayout.setVerticalGroup(
            panelOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                        .addComponent(listaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaJugadorActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        
        if(producto.getSelectedItem().toString().equals("municiones")){
                panelOpcion.setVisible(false);
                panelOpcion.removeAll();
                agregarCompraMuniciones();
        } else if(producto.getSelectedItem().toString().equals("Arcenal")){
            panelOpcion.setVisible(false);
            panelOpcion.removeAll();
            agregarComprarArma();
        }
        
    }//GEN-LAST:event_productoActionPerformed

    private void agregarCompraMuniciones(){
        panelOpcion.setVisible(true);
        panelOpcion.add(municiones);
        municiones.setSize(800, 300);
        panelOpcion.setPreferredSize(new Dimension(800, 300));
        municiones.setVisible(true);
        panelOpcion.revalidate();
    }
    
    private void agregarComprarArma(){
        panelOpcion.setVisible(true);
        panelOpcion.add(armas);
        armas.setSize(700, 400);
        panelOpcion.setPreferredSize(new Dimension(700, 300));
        armas.setVisible(true);
        panelOpcion.revalidate();
    }
    
    private void diseño(){
        
    }

        
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JComboBox<String> listaJugador;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelOpcion;
    private javax.swing.JComboBox<String> producto;
    // End of variables declaration//GEN-END:variables
}
